### ISSUE TITLE
problem with setting up https://www.github.com/Maluuba/bokeh

### ISSUE THREAD

**Issue by sidharthrai** [Maluuba/FigureQA#4]
Hi All,
I'm working on the prerequisites step 1: that is installing https://www.github.com/Maluuba/bokeh

I have followed all the steps in the instruction but the problem is arising whenever I'm trying to do step 9 i.e.
`python setup.py install --build-js`

When I run this command it is creating the error message below.

Building BokehJS... Failed.

ERROR: 'gulp build' returned the following

---- on stdout:
    

---- on stderr:
    (node:24913) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    (Use `node --trace-deprecation ...` to show where the warning was created)
    AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Task function must be specified
        at Gulp.set [as _setTask] (/home/sidharth/Documents/FigureQA/bokeh/bokehjs/node_modules/undertaker/lib/set-task.js:10:3)
        at Gulp.task (/home/sidharth/Documents/FigureQA/bokeh/bokehjs/node_modules/undertaker/lib/task.js:13:8)
        at Object.<anonymous> (/home/sidharth/Documents/FigureQA/bokeh/bokehjs/gulp/tasks/build.ts:4:6)
        at Module._compile (node:internal/modules/cjs/loader:1101:14)
        at Module.m._compile (/home/sidharth/Documents/FigureQA/bokeh/bokehjs/node_modules/ts-node/src/index.ts:392:23)
        at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
        at Object.require.extensions.<computed> [as .ts] (/home/sidharth/Documents/FigureQA/bokeh/bokehjs/node_modules/ts-node/src/index.ts:395:12)
        at Module.load (node:internal/modules/cjs/loader:981:32)
        at Function.Module._load (node:internal/modules/cjs/loader:822:12)
        at Module.module.constructor.require (/home/sidharth/Documents/FigureQA/bokeh/bokehjs/gulpfile.js:11:29) {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='
    }

I have tried a few different things to solve the problem which includes following the instructions of 
https://github.com/Maluuba/bokeh/issues/8

decreasing the version of gulp (sorry can remember the versions now ), nodejs from latest to 10,  8, 6

Not only that I have tried a few more solutions like following the instructions from the link below.
https://github.com/bokeh/bokeh/issues/7854

I still cannot solve the issue. Can you please help me out? Please let me know if you have any questions for me regarding the problem or 
Thank you so much in advance for trying to help me out.

Secondly,  I will appreciate it if you can suggest me some annotation tools which I can use for annotating the graphs.

Thank you so much once again, please let me know if you have any questions for me.

**Comment by MarcWong** [comment]
Solved it by downgrading many packages:

npm v6.4.1
node v11.15.0
gulp@3.9.1
gulp-coffee@2.3.5
jquery@3.6.0
jquery-ui@1.10.1
jquery-mousewheel@3.1.13
